apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus
  name: prometheus-federation
  namespace: kube-system
spec:
  endpoints:
  - interval: 60s
    scheme: http
    path: /federate
    scrape_timeout: 30s
    honor_labels: true
    params:
      'match[]':
        - '{__name__=~".*:.*"}'
  selector:
    matchLabels:
      app: prometheus
