apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      initContainers:
      - name: chown
        image: cr.d.xiaomi.net/containercloud/busybox:latest
        command:
        - chown
        - nobody
        - /prometheus/data
        volumeMounts:
        - name: data
          mountPath: "/prometheus/data"
      containers:
      - name: prom-reloader
        image: cr.d.xiaomi.net/containercloud/prom-reloader:mpath
        imagePullPolicy: Always
        args:
        - --v
        - --t
        - --p=/etc/prometheus
        - --c=curl -XPOST -sS -f http://localhost:9090/-/reload
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      - name: prometheus
        image: cr.d.xiaomi.net/containercloud/prometheus:v2.15.1
        imagePullPolicy: Always
        args:
        - --config.file=/etc/prometheus/prometheus-config.yaml
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --storage.tsdb.path=/prometheus/data
        - --storage.tsdb.retention=7d
        - --web.enable-lifecycle
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus/data
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: data
        hostPath:
          path: /home/data/thanos
      dnsPolicy: ClusterFirst
      restartPolicy: Always
