apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: prometheus
        args:
        - --config.file=/etc/prometheus/prometheus-config.yaml
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --storage.tsdb.path=/prometheus/data
        - --storage.tsdb.min-block-duration=2h
        - --storage.tsdb.max-block-duration=2h
        - --storage.tsdb.retention=7d
        - --web.enable-lifecycle
      - name: thanos
        image: quay.io/thanos/thanos:v0.9.0
        imagePullPolicy: Always
        args:
        - sidecar
        - --tsdb.path=/prometheus/data
        - --prometheus.url=http://localhost:9090
        - --objstore.config=$(OBJSTORE_CONFIG)
        ports:
        - containerPort: 10901
          name: grpc
        - containerPort: 10902
          name: http
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-objectstorage
        volumeMounts:
        - name: data
          mountPath: /prometheus/data
