apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - name: prom
    port: 9090
    targetPort: 9090
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http

